### ISSUE TITLE
[FE] My_profile Languages : the "language" and "Knowledge level" fields differ from the planned design / поля «мова» та «рівень знань» відрізняються від запланованого дизайну (к-54)

### ISSUE THREAD

**Issue by KhanAnna** [ratifire/devrate-web#629]
AR:
- The "Knowledge Level" field has a different border when inactive, and in the empty state, the red border is missing.  
- The "Language" field has an auxiliary button that is purple but should be white.  
- The fields do not have a required field indicator.  
corrected - The error message when saving an empty field should be closer to the field (as implemented in the "Contact Information" step 2 for the "Email" field).

ER: 
- the fields are the same and match the intended design

platforma
![Image](https://github.com/user-attachments/assets/a9e22487-d347-4335-ae01-3778af3f4db0)
figma
![Image](https://github.com/user-attachments/assets/8c0cfbcf-a498-4238-af02-e3d328aee8eb)

https://github.com/user-attachments/assets/6bc18224-59c8-482e-97dd-e374ee920981

**Comment by SerjioBlack** [comment]
In the level selection select, the border color will change only when the first select with language selection is filled, this is probably how it is intended in MUI, and the second thing that could not be fixed is that the * symbol is present both inside the select and at the top, because MUI uses the same label in both places. We need to check with the designers or Alexander whether we will leave this option or look for other ways

**Comment by KhanAnna** [comment]
![Image](https://github.com/user-attachments/assets/1ecea08c-5913-4c13-8ad1-3d0373aa6e0e)

**Comment by OksanaTrokoz** [comment]
Bug was fixed
![Снимок экрана 2024-11-27 185708](https://github.com/user-attachments/assets/6caac24d-eb26-4052-ba15-9016ffa2e8e5)
![Снимок экрана 2024-11-27 185648](https://github.com/user-attachments/assets/1f6c0c7a-66dd-4ece-ad1a-4ec7abdd1d7e)
